services:
  mongodb1:
    image: mongo:7.0
    container_name: mongodb1
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: reptiles
    volumes:
      - mongodb1-data:/data/db
    networks:
      - kmidbt-net
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb1:27017'},{_id:1,host:'mongodb2:27017'},{_id:2,host:'mongodb3:27017'}]}) }" | mongosh -u admin -p reptiles --authenticationDatabase admin
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongodb2:
    image: mongo:7.0
    container_name: mongodb2
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: reptiles
    volumes:
      - mongodb2-data:/data/db
    networks:
      - kmidbt-net

  mongodb3:
    image: mongo:7.0
    container_name: mongodb3
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: reptiles
    volumes:
      - mongodb3-data:/data/db
    networks:
      - kmidbt-net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: reptiles
      ME_CONFIG_MONGODB_URL: mongodb://admin:reptiles@mongodb1:27017,mongodb2:27017,mongodb3:27017/?replicaSet=rs0
      ME_CONFIG_BASICAUTH: false
    networks:
      - kmidbt-net
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3

volumes:
  mongodb1-data:
  mongodb2-data:
  mongodb3-data:

networks:
  kmidbt-net:
